version: "3"
services:
    auctionservice:
      network_mode: host
        container_name: auctionservice
        build:
            context: ../src/auctionservice
            dockerfile: Dockerfile
        image: auctionservice
        environment:
            BID_DELAY: 200
        ports:
            - "8080:8080"

    bidderservice:
      network_mode: host
        container_name: bidderservice
        build:
            context: ../src/bidderservice
            dockerfile: Dockerfile
        image: auctionservice
        environment:
            AUCTION_SERVICE_URL: http://auctionservice
            BID_DELAY: 200
        ports:
            - "3000:3080"
        depends_on:
            - auctionservice
