version: "3"
services:
    auctionservice:
        container_name: auctionservice
        build:
            context: ../src/auctionservice
            dockerfile: Dockerfile
        image: auctionservice
        environment:
            BID_DELAY: 200
        ports:
            - 8080:8080

    bidderservice:
        build:
            context: ../src/bidderservice
            dockerfile: Dockerfile
        image: bidderservice
        environment:
            AUCTION_SERVICE_URL: http://auctionservice:8080/auction/bidder
            BID_DELAY: 200
            PORT: 3000
        depends_on:
            - auctionservice
        ports:
            - 3000:3000

networks:
    host:
        external: true
